apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  namespace: sample-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: REPLACE_WITH_IMAGE_SERVICE_B
        ports:
        - containerPort: 3000
